font_size 18
confirm_os_window_close 0
copy_on_select clipboard
clipboard_control write-clipboard read-clipboard write-primary read-primary
scrollback_lines 1000
modify_font cell_height 2px
window_padding_width 4
cursor_blink_interval 0
shell_integration no-cursor
