# font-family = Iosevka
# font-family = MesloLGSDZ Nerd Font Mono
# font-family = GeistMono Nerd Font Mono
# font-family = ZedMono Nerd Font Mono
# font-family = DejaVuSansM Nerd Font Mono
# font-family = CommitMono Nerd Font Mono
# font-family = 0xProto Nerd Font Mono
# font-family = Adwaita Nerd Font Mono
# font-family = Maple Mono

# font-family = Hack Nerd Font Mono

# font_family UbuntuMono Nerd Font Mono
# font_family ZedMono Nerd Font Mono
font_family AdwaitaMono Nerd Font Mono
font_size 18
# font_size 20
confirm_os_window_close 0
copy_on_select clipboard
macos_option_as_alt yes
clipboard_control write-clipboard read-clipboard write-primary read-primary
scrollback_lines 1000
macos_thicken_font 0.25
modify_font cell_height 2px
window_padding_width 4
cursor_blink_interval 0
shell_integration no-cursor
